name: Open Data Auto Update

on:
  schedule:
    - cron: '0 18 * * *' # 日本時間の午前3時に毎日実行
  workflow_dispatch: # 手動実行ボタンを出すための設定

jobs:
  update-csv:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 書き込み権限を明示的に許可
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Directories
        run: |
          mkdir -p area/kanagawa/kawasaki

      - name: Download CSV Files
        run: |
          curl -L "https://www.city.kawasaki.jp/170/cmsfiles/contents/0000116/116229/141305_public_facility.csv" -o area/kanagawa/kawasaki/kawasaki-barrierfree.csv

      - name: Commit and Push
        run: |
          git config --local user.name "PocketPortal-Bot"
          git config --local user.email "action@github.com"
          git add .
          git commit -m "Auto-update: $(date +'%Y-%m-%d')" || true
          git push
