name: Open Data Auto Update

on:
  schedule:
    - cron: '0 18 * * *' # 日本時間の午前3時に毎日実行
  workflow_dispatch: # 手動実行用

jobs:
  update-csv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Directories
        run: |
          mkdir -p area/kanagawa/kawasaki

      - name: Download CSV Files
        run: |
          curl -L "https://data.city.kawasaki.jp/dataset/866d03f6-43e7-498c-8519-755d40908865/resource/46944e97-e85c-4a37-84a1-096057018399/download/shisetsu_ichiran.csv" -o area/kanagawa/kawasaki/kawasaki-barrierfree.csv

      - name: Commit and Push
        run: |
          git config --local user.name "PocketPortal-Bot"
          git config --local user.email "action@github.com"
          git add .
          git commit -m "Auto-update Open Data: $(date +'%Y-%m-%d')" || true
          git push
